
name: 部署远端服务器

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: 安装依赖
        run: npm ci

      - name: 下载 agile 全家桶
        shell: bash
        run: |
          AGILE_PACKAGES=(

              "https://github.com/loogg/agile_upgrade"
              "https://github.com/loogg/agile_telnet"
              "https://github.com/loogg/agile_modbus"
              "https://github.com/loogg/agile_led"
              "https://github.com/loogg/agile_jsmn"
              "https://github.com/loogg/agile_ftp"
              "https://github.com/loogg/agile_console"
              "https://github.com/loogg/agile_button"
          )

          cd src/agile_packages
          for var in ${AGILE_PACKAGES[@]}; do
            url=$var
            git clone ${url}
            name=${url##*/}
            cd ${name}
            find *|grep -v '\<README.md\|figures\>' |xargs rm -rf .* || true
            sed -i "1i ---\r\nicon: module\r\narticle: false\r\nlastUpdated: false\r\ncontributors: false\r\neditLink: false\r\n---\r\n" README.md
            cd ..
            sed -i "11i \      { text: \"${name}\", icon: \"github\", link: \"${url}\" }," ../.vuepress/navbar.ts
            sed -i "5i \    \"${name}/\"," ../.vuepress/sidebar.ts
          done
          ls

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          npm run docs:build
          > src/.vuepress/dist/.nojekyll

      - name: 部署远端服务器
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "src/.vuepress/dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
